src/context.rs
This is an alternative structure for this loop.
=> Clean up main loop

src/context.rs
I added the tests from my review.
=> More tests for events

src/context.rs
=> Ranya simulation halt

Cargo.toml, examples/reports-multi-threaded/main.rs, examples/reports/main.rs, src/lib.rs, src/report.rs
=> Implement report.rs component

examples/basic-infection/README.md
I carefully reviewed the document and although I realize this was written to be more "pseudo-codeish" and provide a framework for development, I found several areas where I thought more claritiy could help.
=> Editorial changes

.gitignore, examples/basic-infection/README.md, examples/basic-infection/incidence_report.rs, examples/basic-infection/infection_manager.rs, examples/basic-infection/main.rs, examples/basic-infection/people.rs, examples/basic-infection/plot_output.R, examples/basic-infection/transmission_manager.rs
Added a set of modules that implement an infection manager and a transmission manager
=> Code to implement example #1 (basic infection)

src/people.rs
Bandage solution to #60 and #61
=> Only return person ids for people that exist in the simulation so far

examples/basic-infection/incidence_report.rs, examples/basic-infection/main.rs, examples/births-deaths/demographics_report.rs, examples/births-deaths/incidence_report.rs, examples/births-deaths/main.rs, examples/parameter-loading/incidence_report.rs, examples/parameter-loading/main.rs, examples/reports-multi-threaded/main.rs, examples/reports/main.rs, examples/time-varying-infection/incidence_report.rs, examples/time-varying-infection/main.rs, examples/time-varying-infection/periodic_report.rs, src/report.rs
Report errors are bubbled up into `IxaError`.
=> Don't automatically overwrite reports

examples/time-varying-infection/periodic_report.rs, examples/time-varying-infection/plot_output.R, src/context.rs, src/report.rs
Self scheduling periodic report that implements a given closure with a given periodicity.
=> Add periodic report

src/error.rs
I just did this the same way I did it for `IOError` before. But, let me know if there's something else wanted here. Thanks!
=> More error types

.github/workflows/docs.yml
=> Build docs

src/report.rs, src/runner.rs, tests/bin/runner_test_custom_args.rs
I cleaned up some of the `Arg` definitions also (like using `Option` property and `PathBuf` directly)
=> Add additional options to runner

Cargo.toml, src/runner.rs, src/web_api.rs
@k88hudson-cfa you should hold off on reviewing this until you have reviewed #169, because this stacks on #169.
=> Add a CSRF secret. Fixes #172.

.pre-commit-config.yaml, Cargo.toml
Fixes #177
I thought this might be helpful given we're running into a few more things that are annoying / we might want to turn off
=> Move clippy configuration to Cargo.toml

Cargo.toml, src/web_api.rs
We'll eventually probably want to have some way to pick the directory, but I haven't worked out the details yet, and this is enough for development
=> Add support for serving static files

src/people/context_extension.rs, src/people/data.rs, src/people/external_api.rs, src/people/index.rs, src/people/methods.rs, src/people/mod.rs
This is preparation for adding new methods that clearly aren't index-affiliated.
=> Refactor out synthesized methods

src/people/query.rs
This is needed for situations where you need to iterate over multiple queries given some query from a function (such as when you're looking for a next contact)
=> Implement clone for QueryAnd

src/people/context_extension.rs, src/people/property.rs
@em-gr does this fix your issue?
=> Remove spurious comma. Fixes #199

src/global_properties.rs, src/lib.rs, src/random.rs
=> Re-export rand, ctor, paste

.devcontainer/devcontainer.json, src/web_api.rs
also added pre-commit to the project codespace.
=> Adjusting web path to project root #200

examples/births-deaths/src/population_manager.rs, src/people/context_extension.rs
=> Return an Option from sample_person

examples/basic/main.rs, scripts/setup_new_ixa_project.sh, scripts/template/.github/workflows/build-test.yaml, scripts/template/.github/workflows/pre-commit.yaml
using the script should be documented in the book:
`export ixa_branch=release && curl -s --variable %B=$ixa_branch --expand-url https://raw.githubusercontent.com/CDCgov/ixa/{{B:url}}/scripts/setup_new_ixa_project.sh | sh -s $ixa_branch`
for testing until this is merged you can run:
`export ixa_branch=cdc-as81-script-to-setup-new-ixa-project-#221 && curl -s --variable %B=$ixa_branch --expand-url https://raw.githubusercontent.com/CDCgov/ixa/{{B:url}}/scripts/setup_new_ixa_project.sh | sh -s $ixa_branch`
=> added script to setup new ixa projects

Cargo.toml, ixa-derive/Cargo.toml
=> fix: Update the derive crate to have correct version

docs/CONTRIBUTING.md
This could have more in it, but I added details about commit messages and releasing to start
=> chore: Add contributor docs

Cargo.toml
This accidentally got introduced by a rebase
=> fix: Restore workspace, correct versions to Cargo.toml

ixa-bench/Cargo.toml
This still needs https://github.com/CDCgov/ixa/pull/326 to fix the issue with pull request benchmarks not producing output
=> chore: Add bench=false to benchmarks package

Cargo.toml, src/external_api.rs, src/random.rs
replacing StdRng with SmallRng
https://docs.rs/rand/latest/rand/rngs/struct.SmallRng.html#
=> feat: Use a fast pseudorandom number generator

README.md, docs/book/src/appendix_rust/appendix-rust.md, docs/book/src/appendix_rust/rust-resources.md, docs/book/src/get-started.md
I finally got around to collating the resources I tend to send people when they are first learning Rust for ixa development. I try to emphasize patterns that come up a lot when writing ixa code but that the Rust book doesn't emphasize as much.
This very much represents my opinion on what topics are most important to learn, so please feel free to add or suggest I axe things.
I hope that this will get updated as ixa development continues!
=> feat: Resources for learning Rust for ixa development

.pre-commit-config.yaml
=> Disable markdown lint

.gitignore, src/execution_stats.rs, src/external_api.rs, src/global_properties.rs, src/people/external_api.rs, src/runner.rs
Also added missing generated docs output to `.gitignore`.
=> fix: Silenced a handful of warnings that are only emitted for the `web_api` feature.

examples/load-people/vaccine.rs, src/context.rs, src/data_plugin.rs, src/global_properties.rs, src/lib.rs, src/network.rs, src/people/external_api.rs, src/plugin_context.rs, src/prelude.rs, src/random.rs, src/report.rs
=> feat: Extend PluginContext to include base plugins
