- .github/workflows/build-test.yaml
- .pre-commit-config.yaml
I often find the clippy `pedantic` argument to be helpful. Feel free to ignore and close this PR.
This *would* be better as a pre-commit, but I could not for the life of me figure out how to pass in the `-W clippy::pedantic` argument to the pre-commit config; it just kept skipping over it, or saying it got an unexpected argument. I figured "better late (in the PR process) than never" applied here.
> Run pedantic clippy in CI

- Cargo.toml
- src/context.rs
- src/lib.rs
- src/main.rs
- src/plan.rs
This imports the code from `eosim` for Context.
> Add Context - resolves #1

- examples/reports-multi-threaded/README.md
- examples/reports-multi-threaded/main.rs
- examples/reports/README.md
- examples/reports/main.rs
This PR adds a skeleton for report writing examples which will support Ranya's work in https://github.com/CDCgov/ixa/issues/22, which will implement a report writing module.
You can run examples with `cargo run --example reports` etc.
> Added two reports examples

- examples/reports-multi-threaded/main.rs
This PR adds a report writing example for multi-threading, which will implement the report writing module.
You can run examples with cargo run --example reports-multi-threaded.
> Report Example for Multi-Threading

- Cargo.toml
- src/lib.rs
- src/random.rs
This PR adds a module to support creating and using random generators. It's implemented as a trait on context, with a `DataPlugin` to store a base random seed and a hashmap of rng instances. The design supports any rng implementation that implements `rand::SeedableRandom`.
The basic idea is you initialize the utility with a base random seed when setting up a `context`:
```rust
context.set_base_random_seed(12345678);
```
In a module that needs an independent random number generator, you use a macro to define an independent type, and then call `context.get_rng::<YourType>()` to retrieve it. For example:
```rust
define_rng!(FooRng)
let mut rng = context.get_rng::<FooRng>();
let value = rng.next_u64();
```
Note that an `rng` needs a mutable reference because it has to store internal state …
> Added random module

- src/context.rs
- src/random.rs
This improves ergonomics of `DataPlugins` by allowing calls like `context.get_data_plugin(MyDataPlugin)` in place of the turbofish.
> Switch DataPlugins to use struct type indicator

- examples/load-people/README.md
- examples/load-people/logger.rs
- examples/load-people/main.rs
- examples/load-people/people.csv
- examples/load-people/population_loader.rs
- examples/load-people/sir.rs
- examples/load-people/vaccine.rs
- src/lib.rs
- src/people.rs
- src/random.rs
This is an alternative implementation of people/person properties which primarily uses initializers to assign initial property values during person creation.
The README below has a full explanation of the interfaces (I'd recommend reading that) as demonstrated by an example. 
I previously pushed a previous implementation of people/person properties which uses immediate events (you can see in the commit history), where you add `before_person_creation` or `set_default` hooks prior to `add_person` being called. The main downside of this was that you had to be careful about initialization order and it was somewhat counter-intuitive to read:
```rs
context.before_person_added(move |context, person_id| {
context.set_person_property(person_id, Age, record.age); …
```
> Add Person Properties

- Cargo.toml
- examples/basic-infection/people.rs
- ixa-derive/Cargo.toml
- ixa-derive/src/lib.rs
- src/context.rs
- src/people.rs
This implementation supports multiple property dependencies and computes values lazily for derived properties (avoiding some of the mechanics around updating the cache and therefore the need to register early). Registration happens during subscription only; we will also need to do this during index creation). 
I avoid wrapping the events with a special function by implementing a `on_subscribe` hook on an `Event` trait.
> Derived properties

- src/context.rs
- src/plan.rs
This pull request introduces a new method to check if there are more plans to be evaluated and adds corresponding tests to ensure the new method's functionality. Essentially, a method is added to the `Queue` object to evaluate whether there are more plans sitting on the `BinaryHeap` that stores the sorted plans. This helper method is then called from `Context`'s realization of the queue object and returns whether there are more plans to be executed. Having two methods is necessary because we don't want to expose the `plan_queue` directly to the user, and the internal `BinaryHeap` in `Queue` is private to `plan.rs`.
These new methods take immutable references to `context`.
> Does context have more plans left to evaluate?

- Cargo.toml
- examples/time-varying-infection/README.md
- examples/time-varying-infection/exposure_manager.rs
- examples/time-varying-infection/incidence_report.rs
- examples/time-varying-infection/infection_manager.rs
- examples/time-varying-infection/input.json
- examples/time-varying-infection/main.rs
- examples/time-varying-infection/parameters_loader.rs
- examples/time-varying-infection/periodic_report.rs
- examples/time-varying-infection/plot_output.R
- examples/time-varying-infection/population_loader.rs
Introduces two ways of modeling time-varying rates in `ixa` and Rust -- in particular, a seasonal force of infection and a recovery rate that scales with the number of infected people. This PR and the readme focuses on _how_ to model time-varying rates and different methods of doing so.
The example is the same as the basic-infection example, except that it:
1. Has been updated to include the built-in `people` module. The tests can therefore be a bit more intense and are properly updated.
2. Has been updated to include the built-in `global_properties` module. The R code also reads from the json file and some small bugs in the R code have been cleaned up.
3. A periodic report has been added!
> Example of time-varying rates

- examples/parameter-loading/incidence_report.rs
- examples/parameter-loading/infection_manager.rs
- examples/parameter-loading/main.rs
- examples/parameter-loading/transmission_manager.rs
- examples/time-varying-infection/exposure_manager.rs
- examples/time-varying-infection/incidence_report.rs
- examples/time-varying-infection/infection_manager.rs
- examples/time-varying-infection/main.rs
- examples/time-varying-infection/periodic_report.rs
- examples/time-varying-infection/population_loader.rs
- src/global_properties.rs
Returns None when either:
- No global properties have been set
- Global properties exist but the requested property has not been set.
> Change |get_global_property()| to return Option<&T::Value>. Fixes #72

- examples/births-deaths/population_manager.rs
- examples/load-people/population_loader.rs
- examples/load-people/sir.rs
- examples/parameter-loading/infection_manager.rs
- examples/parameter-loading/main.rs
- examples/parameter-loading/transmission_manager.rs
- examples/time-varying-infection/exposure_manager.rs
- examples/time-varying-infection/infection_manager.rs
- examples/time-varying-infection/population_loader.rs
- src/people.rs
This PR adds the ability to initialize properties in `add_person()`, as in:
```
let person = context.add_person(((Age, 17), (IsSwimmer, true))).unwrap()
```
Any non-derived property that doesn't have automatic initialization must be initialized in this fashion during creation, which means we have removed `initiialize_person_property()`. This is technically enforced by checking that any known such property is present in the initialization list. This enforcement is imperfect because `Context` doesn't know about any property which has never been used. This means that if you do `add_person()` followed by `get_person_property()` for such a property, it will panic. However, as long as there is any use of a property this invariant will instead be enforced in `add_person()`
> Initialize properties in add_person

- src/report.rs
Kate rightly pointed out that the updated test for writing a file with no directory specified could error out before the "remove file" step. Based on her suggestion, I reimplemented that step in a `Drop` trait so that it automatically happens even if the test errors out earlier.
Doing this made me catch a few places where I believe `clone` was used extraneously. However, please correct me if I am wrong.
> Report test: remove written files to working dir automatically

- src/lib.rs
- src/network.rs
- src/people.rs
- src/random.rs
A network is modeled as a directed graph.  Edges are typed in the usual fashion, i.e., keyed by a Rust type, and each person can have an arbitrary number of outgoing edges of a given type, with each edge having a weight, as in:
context
.add_edge::<EdgeType1>(person1, person2, 0.01);
context
.add_edge::<EdgeType1>(person1, person3, 0.02);
Which creates a graph where `person1` has two outgoing edges of type `EdgeType`, to `person2` and `person3`.
Edges are directional but `add_edge_bidi()` will create one edge in each direction between two people with the same weight for both edges. If you want to create edges with different weights, you have to do it separately.
Creating an edge to yourself is forbidden (returns IxaError). It is not technically possible to create an edge to a person who …
> Initial implementation of a network facility.

- src/error.rs
Added the ParseIntError to the IxaError `enum` to propagate errors expected in ixa-epi-isolation when selecting digits from integers as strings.
> Added ParseIntError to IxaError

- Cargo.toml
- examples/runner/main.rs
- src/global_properties.rs
- src/lib.rs
- src/runner.rs
- tests/bin/runner_test_custom_args.rs
- tests/data/global_properties_runner.json
I still need to add custom arg parsing, but here is a start to a runner with some base arguments and generic setup functionality.
> Add runner with arg parsing

- Cargo.toml
- examples/runner/main.rs
- src/context.rs
- src/debug.rs
- src/debugger.rs
- src/lib.rs
- src/plan.rs
- src/runner.rs
- tests/bin/runner_test_debug.rs
This PR adds a basic cli debugger
> MVP debugger

- examples/parameter-loading/transmission_manager.rs
- src/people.rs
- src/random.rs
The original `sample_person()` would query over the entire population. With this change you can provide a `query_people()` style query and it will sample over the matching subset.
For whole-population queries, we just draw a random value from the population size.
For subset queries, to avoid allocating a vector with all the matching people, this uses the efficient Reservoir Sampling algorithm published by Kim-Hung Li.
> Changed `sample_person()` to take a query

- Cargo.toml
- src/debugger.rs
This adds support for history editing via rustyline.
Before we land this, we should address the behavior under the following conditions:
* Ctrl-D -- usually end of data
* Ctrl-C -- usually interrupt
In the current code prior to this PR, C-c causes termination and C-d causes the prompt to reprint. By contrast, here is LLDB
```
20:52:35|~/dev/cfa/ixa (ekr_issue126_rustylines)$ lldb
(lldb) ^D
20:52:41|~/dev/cfa/ixa (ekr_issue126_rustylines)$ lldb
(lldb) ^C
(lldb) ^C
(lldb)
```
In
> Initial rustyline integration. Fixes #126

- src/context.rs
- src/debugger.rs
- Add persistent state (mostly for rustyline support)
- Have `process_command()` (formerly `process_line()`) return a string rather than try to write to `T: Write`.
- Remove the mocks that were needed for testing because of the previous item
> Some changes to make the debugger more flexible

- examples/runner/main.rs
- src/debugger-commands.md
- src/debugger.rs
- src/global_properties.rs
- src/runner.rs
This PR adds a `global` command to the debugger, which prints the value of a registered global property to the console.
If you type `global` (with no argument) or with an invalid property name, you will see a list of available properties:
```
t=0 $ global
2 global properties registered:
runner.FavoriteNumber, runner.Name
```
If you provide a valid, fully qualified property name, you will see the value:
```
t=0 $ global runner.Name
"Sim123"
```
> Add global command to the debugger

- src/debugger.rs
This is groundwork for the Web API, where I want to use JSON as the interchange language, and this will allow us to use common for the debugger and the Web API once you get past the parser.
> Restructure debugger to use the clap derived API.

- src/global_properties.rs
- src/people.rs
Fixes #165 by adding support for global properties which are assumed to be immutable, and read the first time the property is accessed. Note that there is no infrastructure to watch for changes to global properties.
I kind of prefer version A (which is what I've implemented here) but I think we could consider B
```rust
// A, combined arguments
define_derived_property!(IsEligible, bool, [Age], |age| age >= 18);
define_derived_property!(IsEligible, bool, [Age], [Threshold], |age, threshold| {
age >= threshold
});
// B, tuples
define_derived_property!(IsEligible, bool, [Age], |(age)| age >= 18);
define_derived_property!(IsEligible, bool, [Age], [Threshold], |(age), (threshold)| {
age >= threshold
});
```
> Add global properties to derived property macro

- src/people/context_extension.rs
- src/people/mod.rs
- src/people/query.rs
My use case here is that I'd like to support being able to construct queries across function boundaries, for example:
```rust
fn get_susceptible_people<Q>(context: &Context, q) where Q: Query {
let base_query = ((Alive, true), (InfectionStatus, InfectionStatusValue::Susceptible));
context.query_people(query_add(q, base_query));
}
let other_properties = ((RiskCategory, RiskCategory::High), (Region, CA));
let people = get_susceptible_people(context, extra_query); 
```
> Added query_and utility

- src/external_api.rs
- src/people/context_extension.rs
- src/people/external_api.rs
- src/report.rs
- src/tabulator.rs
- src/web_api.rs
This exposes an external API to allow you to tabulate person properties. The major difference from the internal API is that it takes property names as strings. This API is plumbed up to the Web API but could also be plumbed to the debugger.
> Add an external tabulate API.

- examples/time-varying-infection/main.rs
This should have been caught in CI. I'm going to add some CI for examples in a separate PR.
> Fix argument parsing for time-varying-infection

- Cargo.toml
- examples/births-deaths/src/infection_manager.rs
- examples/births-deaths/src/parameters_loader.rs
- examples/load-people/population_loader.rs
- examples/time-varying-infection/exposure_manager.rs
- src/context.rs
- src/debugger.rs
- src/global_properties.rs
- src/hashing.rs
- src/lib.rs
- src/log.rs
- src/network.rs
- src/people/context_extension.rs
- src/people/data.rs
- src/people/external_api.rs
- src/people/index.rs
- src/people/mod.rs
- src/plan.rs
- src/random.rs
- src/report.rs
- src/web_api.rs
All instances of `HashMap` and `HashSet` now import from the crate root so that it is easy to replace implementation. 
Deterministic implementations of both data structures are provided in `hashing.rs`. 
The same deterministic algorithm is used in `random.rs` for name offset in RNGs.
Fixed a bug in `get_rng()` where adding the seed offset might saturate.
Allowed "implicit hasher" for clippy.
This PR addresses the following issues:
- #222 
- #265 
- #272
> All instances of `HashMap` and `HashSet` now deterministic.

- .github/workflows/release-plz-pr.yaml
- .github/workflows/release-plz-release.yaml
- .github/workflows/release-plz.yaml
- Cargo.toml
- examples/births-deaths/src/incidence_report.rs
By default, version and changelog should be updated automatically by release-plz.
if we need to set a version, we can run locally:
`release-plz set-version 1.2.3  `
Note that the action creates a PR, we can edit the PR before merge.
> feat: add release-plz action

- Cargo.toml
- src/context.rs
- src/debugger-commands.md
- src/debugger.rs
- src/external_api.rs
- src/plan.rs
- src/runner.rs
- src/web_api.rs
- static/src/api.js
- static/src/app-state.js
- It reuses `plan::Queue` for `Context::breakpoints_scheduled`, but I implemented `next_time()` and `peek()` on it, the latter of which required that `Entry<P>` be `pub(crate)`. 
- `Context::request_debugger()` and `Context::cancel_debugger_request()` are a setter and resetter respectively for `Context::break_requested`, which works like `Context::shutdown_requested()` but takes priority.
- Breakpoints scheduled at a particular time run before the next scheduled plan if the time of the next scheduled plan is `<=` or `<`, according to whether the breakpoint was scheduled with `ExecutionPhase::First` or `ExecutionPhase::Last`. (What about `ExecutionPhase::Normal`?)
- The "next" command that takes a time has been renamed to "breakpoint", and a new "next" command was created. In other words: …
> Breakpoint, "next", and "halt" implementation. Fixes #163.

- docs/book/src/first_model/setup.md
- src/global_properties.rs
- src/network.rs
- src/runner.rs
- src/web_api.rs
Fixed broken `include` in the Ixa book introduced by automated Rust formatting. Line lengths were also brought into line with our lints.
The `#include` is embedded in a Rust code fench:
````
```rust
// main.rs
{{ #include ../../models/basic/main.rs}}
```
````
"Autoformat on save" tries to format the `include` as Rust code and mangles it.
> fix: Fixed broken `include` in the Ixa book. Fixes #302.

- .github/workflows/build-test.yaml
- .github/workflows/pull_request.yaml
This WIP PR integrates benchmarks into CI. There are two primary tasks:
1. Build benchmarks
2. Run benchmarks and compare to baseline to detect performance regressions
The first is trivial. The second is complicated.
> Integrate Benchmarks Into CI

- src/people/context_extension.rs
- src/people/data.rs
- src/people/mod.rs
- src/people/property.rs
AFAICT the bug seemed to be introduced by ee3c219bed26fd8251ea8644b5ecd263c0186023 when we started registering all properties during get_person_property etc.
I agree we should take a look at refactoring/cleaning a bunch of this up but it would be good to add some more tests about initialization semantics/indexing before we do that.
> Fix double borrow during property registration

- examples/network-hhmodel/seir.rs
- src/people/context_extension.rs
- src/people/index.rs
- src/people/property.rs
- src/people/query.rs
Adding support for multi property index
usage:
if you have the following properties defined: Age, County, Height
in your function you can call:
define_multi_property_index!(AgeCountyHeight, [Age, County, Height]);
and now you can just query the defined properties, like:
let result = context.query_people(((Height, 140), (County, 1), (Age, 28)));
> feat: Support multi-property indexes

- docs/book/src/first_model/transmission.md
I believe that the line
https://github.com/CDCgov/ixa/blob/4be6bca8e436481a935720caefefcd7fdac034ff/docs/book/models/disease_model/src/transmission_manager.rs#L10
is missing from the following code chunk:
> Change range of lines of code to display define_rng!

- docs/book/src/first_model/infection.md
- docs/book/src/first_model/next-steps.md
- docs/book/src/first_model/people.md
- docs/book/src/first_model/reporter.md
- docs/book/src/first_model/setup.md
- docs/book/src/first_model/transmission.md
- docs/book/src/get-started.md
Fixes #315  
See https://rust-lang.github.io/mdBook/format/mdbook.html#including-a-file-but-initially-hiding-all-except-specified-lines
> docs: Use rustdoc_include to link to full files in ixa book

- Cargo.toml
- src/lib.rs
- src/numeric.rs
Vendors `almost_eq`, `convergence`, and the `assert_almost_eq!` macro from statrs@0.18.0 (prec.rs), which are implemented on top of the small `approx` crate.
Added some unit tests as well.
> feat: `almost_eq`, `convergence`, and the `assert_almost_eq!` macro

- Cargo.toml
- examples/basic-infection/Cargo.toml
- examples/births-deaths/Cargo.toml
- ixa-derive/Cargo.toml
- ixa-integration-tests/Cargo.toml
Modified workspace members to opt in to workspace lint exceptions. 
Added `missing_errors_doc = "allow"` for the same reasons as `missing_panics_doc`.
Note that while `examples/births-deaths` and `examples/basic-infection` are not explicitly members of the workspace, for some reason adding the `[lints]` section to their `Cargo.toml` is needed.
> chore: Modified workspace members to opt in to workspace lint exceptions.  Fixes #339.

- Cargo.toml
Since we're adding more and more workspace crates...
> chore: Use glob pattern for workspace members

- Cargo.toml
- examples/basic-infection/Cargo.toml
- examples/births-deaths/Cargo.toml
- ixa-bench/Cargo.toml
- ixa-derive/Cargo.toml
- ixa-fips/Cargo.toml
- ixa-integration-tests/Cargo.toml
Dependencies are now listed in `[workspace.dependencies]` in the root Cargo.toml and are inherited in workspace member packages that depend on them via `my_dependency.workspace = true`.
~This PR is stacked on top of #350.~ (merged)
> chore: Declare workspace dependencies, which members inherit. Fixes #337.

- src/people/context_extension.rs
- src/people/data.rs
- src/people/event.rs
- src/people/index.rs
- src/people/methods.rs
- src/people/mod.rs
- src/people/property.rs
- src/people/query.rs
- src/tabulator.rs
We have `PersonProperty + 'static` all over our public API. This PR adds the `'static` constraint to the `PersonProperty` trait itself and replaces all instances of `PersonProperty + 'static` with just `PersonProperty`:
```rust
pub trait PersonProperty: Copy + 'static {
// ...
}
```
> Added the `'static` constraint to `PersonProperty`

- ixa-fips/README.md
- ixa-fips/src/errors.rs
- ixa-fips/src/fips_code.rs
- ixa-fips/src/lib.rs
- ixa-fips/src/states.rs
Because the data ranges are nonobvious, I thought it would be helpful to have more helpful error messages when there is a data out of range error. 
- Added `FIPSError` for representing data out of range errors.
- Changed `FIPSCode::encode_*()` methods to validate according to the actual FIPS standard rather than the field's bitwidth, which is purely incidental.
> feat: Added `FIPSError` for data out of range errors.

- examples/basic-infection/Cargo.toml
- examples/births-deaths/Cargo.toml
- src/lib.rs
- src/report.rs
Exposed dependencies for use in macros.
Modified dependencies of `births-deaths` and `basic-infection` accordingly.
> chore: Exposed dependencies for use in macros. Fixes 352.

- docs/book/models/disease_model/src/incidence_report.rs
- docs/book/models/disease_model/src/infection_manager.rs
- docs/book/models/disease_model/src/main.rs
- docs/book/models/disease_model/src/people.rs
- docs/book/models/disease_model/src/transmission_manager.rs
- docs/book/src/first_model/infection.md
- docs/book/src/first_model/next-steps.md
- docs/book/src/first_model/people.md
- docs/book/src/first_model/reporter.md
- docs/book/src/first_model/setup.md
- docs/book/src/first_model/transmission.md
This PR addresses issue #317. It removes `MAX_TIME` from the transmission manager and adds a plan in main to end the simulation. The exercise remains the same with slightly modified language, and encourages people to explore the `ContextPeopleExt` functionality. It also introduces the `if let Some()` pattern.
The rust snippets of code are also now linked using ANCHORs rather than line numbers to improve robustness.
> Integrating book feedback closes #317

- Cargo.toml
- examples/load-people/README.md
- examples/load-people/vaccine.rs
- src/context.rs
- src/lib.rs
- src/random.rs
This is an implementation of the first part of a new plugin design based on explorations here https://k88hudson-cfa.github.io/ixa-playground/context-as-trait/index.html based on feedback. I implemented it in a way that should be backwards-compatible, but allows people to migrate.
After this, we should follow up with migrating other context extensions; I migrated `Random` as a sanity check
> Add PluginContext trait for Context

- .github/workflows/build-test.yaml
- Cargo.toml
- ixa-integration-tests/Cargo.toml
- src/lib.rs
- src/log/mod.rs
- src/log/null_logger.rs
- src/log/standard_logger.rs
- src/log/wasm_logger.rs
- made log4rs optional
- added a "null" logger that does nothing
- added `wasm` feature flag
- added getrandom wasm support when `wasm` feature enabled
ToDo:
Probably later:
> feat: Wasm Compatibility, including a new Wasm logger

- Cargo.toml
- src/context.rs
- src/lib.rs
- src/log/mod.rs
- src/log/progress_bar_encoder.rs
- src/log/standard_logger.rs
- src/progress.rs
There is a tricky bit to make sure the progress bar doesn't interfere with logging.
Questions:
- Should we have a command line flag that enables a progress bar for the timeline?
- I put it behind a feature flag, but we could include it unconditionally and leave it to the client code to enable it in code.
- Should the feature be enabled by default? The two additional dependencies are pretty small.
> feat: Added a progress bar feature. Fixes 408.

- examples/births-deaths/main.rs
- examples/births-deaths/src/lib.rs
- examples/load-people/population_loader.rs
- examples/network-hhmodel/loader.rs
- examples/network-hhmodel/main.rs
- examples/parameter-loading/main.rs
- examples/reports-multi-threaded/main.rs
- ixa-bench/example_births_deaths/example_births_deaths.rs
Changed in-source references to use `env!("CARGO_MANIFEST_DIR")`, an absolute path, instead of the `file!` macro, which is relative. This appears to be a little more robust for certain edge cases (`births-deaths`).
> chore: Made in-source references to input files for examples more robust. Fixes #374.

- docs/book/models/disease_model/Cargo.toml
- docs/book/src/first_model/next-steps.md
- docs/book/src/first_model/people.md
- docs/book/src/first_model/your-first-model.md
[The Ixa Book](https://ixa.rs/book) guides readers through a simple transmission model with a constant force of infection. Because this model has susceptible, infected, and recovered compartments, it is referred to as an SIR model. However, I would suggest that we drop this terminology and explain parenthetically how this model is in fact different from the canonical SIR model (i.e., the Kermack-McKendrick model). I believe these changes would help make the text clearer for persons with a prior background infectious disease modeling. This PR is entirely about documentation and does not include any substantive changes to the example model or code.
> docs: Remove "SIR" terminology from Ixa book

- Cargo.toml
- integration-tests/ixa-wasm-tests/Cargo.toml
Also, a couple of module members did not correctly inherit the lint exceptions from the workspace.
The new lint exceptions are:
- `struct_field_names` - Says that field names of structs should now have the name of the struct as a prefix.
- `unnecessary_debug_formatting` - If we instead use `some_path.display()`, "escaped characters will no longer be escaped and surrounding quotes will be removed." But we prefer escape characters and quotes for our use case.
- `struct_excessive_bools` - Detects when more than three fields of a struct are of type `bool`.
> fix: Silences a few lints new in the latest Rust release. Fixes #440.

- src/people/context_extension.rs
Found an edge case where, if a user asks `sample_people` for a sample of zero people, the code panics instead of just returning an empty list. The code already checked for a zero population size. This PR just moves that check after we take the min of population size and requested sample size.
> fix: Made the check for a request of zero sampled people more robust.

- docs/book/src/SUMMARY.md
- docs/book/src/topics/indexing.md
- docs/book/src/topics/performance.md
- docs/book/src/topics/topics.md
This is part of the work of Issue #434. I thought that indexing deserves its own section.
Tasks required before merging:
> docs: Added a chapter on indexing properties to the ixa book.

- .prettierrc.yaml
- justfile
- Grouped recipes by subject instead of by task
- Fixed bug in `fix-md-file`, added `[no-cd]`
- Made sure installation recipes are idempotent
- Added installation recipes as dependencies to the appropriate recipes
- Created groups to organize `just --list` output
- Added `baseline-create` and `baseline-compare` recipes for benchmark comparisons
- `run-example` recipe now takes an example name
- Made `$RUSTFLAGS="-D warnings"` apply only to `ci` recipe
> chore: Improvements to the justfile

- src/execution_stats.rs
In a previous PR (#489) we exposed `ExecutionStatistics` in the public API for client code to use. But we forgot to make the fields public! Oops. This PR just adds `pub` to each field.
> fix: Made the fields of `ExecutionStatistics` public

- justfile
We decided to commit the generated `cli-usage.md` file after all, but we forgot to modify the `clean-docs` recipe in the `justfile` so that it doesn't clear its contents. This PR fixes `clean-docs` so that it leaves `cli-usage.md` alone.
> fix: Don't empty `cli-usage.md` on `just clean-docs`.

- examples/network-hhmodel/network.rs
- examples/network-hhmodel/seir.rs
- ixa-bench/Cargo.toml
- ixa-bench/criterion/index_benches.rs
- ixa-bench/src/reference_sir/sir_ixa.rs
- justfile
- src/people/context_extension.rs
- src/people/data.rs
- src/people/index.rs
- src/people/property.rs
- src/people/query.rs
- Added `index_benches.rs`.
- Added `with_query_results` method.
- Changed tests to use `with_query_results` instead of `query_people`
This PR is stacked on #534, but it doesn't have to be.
> feat: `with_query_results` API. Fixes #540.
